version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/farm_link
    ports:
      - "3000:3000"
    image: farm_link
    depends_on:
      - db