default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  port: 5432
  
production:
  <<: *default
  database: food_crate_production
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host:  "/cloudsql/farm-link-284523:us-central1:farm-link-db"
  
staging:
  <<: *default
  database: farm_link_staging
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: 127.0.0.1

development:
  <<: *default
  database: farm_link_development
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: farm_link_test
  username: <%= ENV["DB_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
