test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
  service: GCS
  project: farm-link-284523
  credentials: <%= Rails.root.join("config/farm_link.key.as_json") %>
  bucket: farm-link-bucket

# google:
#   service: GCS
#   credentials:
#     type: "service_account"
#     project_id: "farm-link-284523"
#     private_key_id: <%= Rails.application.credentials.dig(:gcskey, :private_key_id) %>
#     private_key: <%= Rails.application.credentials.dig(:gcskey, :private_key).dump %>
#     client_email: "farm-link@farm-link-284523.iam.gserviceaccount.com"
#     client_id: "116276311721033744602"
#     auth_uri: "https://accounts.google.com/o/oauth2/auth"
#     token_uri: "https://accounts.google.com/o/oauth2/token"
#     auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
#     client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/farm-link%40farm-link-284523.iam.gserviceaccount.com"
#   project: "farm-link-284523"
#   bucket: "farm-link-bucket"